name: HAI
channels:
  - defaults
  - anaconda
  - pytorch
dependencies:
  - python=3.10
  - cmake
  - pip
  - pip:
      - numpy==1.24.1
      - tqdm
      - opencv-python
      - scikit-learn
      - pandas
      - matplotlib
      - seaborn
      - yacs
      - imageio
      - grad-cam
